apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: emr-ingress
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /auth
            backend:
              service:
                name: emr-auth
                port:
                  number: 8080
          - pathType: Prefix
            path: /lab
            backend:
              service:
                name: emr-lab
                port:
                  number: 8081
          - pathType: Prefix
            path: /outpatient
            backend:
              service:
                name: emr-outpatient
                port:
                  number: 8082
          - pathType: Prefix
            path: /pharmacy
            backend:
              service:
                name: emr-pharmacy
                port:
                  number: 8083
          - pathType: Prefix
            path: /radiology
            backend:
              service:
                name: emr-radiology
                port:
                  number: 8084
---