apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: emr-auth
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: emr-auth
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: emr-lab
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: emr-lab
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: emr-outpatient
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: emr-outpatient
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: emr-pharmacy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: emr-pharmacy
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: emr-radiology
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: emr-radiology
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
---