apiVersion: apps/v1
kind: Deployment
metadata:
  name: emr-auth
  namespace: default
spec:
  selector:
    matchLabels:
      app: emr-auth
  template:
    metadata:
      labels:
        app: emr-auth
    spec:
      containers:
        - image: leocardhio21/emr-auth:latest
          imagePullPolicy: Always
          name: emr-auth
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "600m"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: emr-config
          env:
            - name: KMS_KEY_NAME
              value: "mongo-auth-symmetric-key"
            - name: SA_PRIVATE_KEY
              value: "SA_PRIVATE_KEY_AUTH"
            - name: JWT_PRIVATE_KEY
              value: "JWT_PRIVATE_KEY"
            - name: DB_PASSWORD
              value: "DB_PASSWORD"
      serviceAccountName: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emr-lab
  namespace: default
spec:
  selector:
    matchLabels:
      app: emr-lab
  template:
    metadata:
      labels:
        app: emr-lab
    spec:
      containers:
        - image: leocardhio21/emr-lab:latest
          imagePullPolicy: Always
          name: emr-lab
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "600m"
          livenessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          ports:
            - containerPort: 8081
              protocol: TCP
          envFrom:
            - configMapRef:
                name: emr-config
          env:
            - name: KMS_KEY_NAME
              value: "mongo-symmetric-key"
            - name: JWT_PUBLIC_KEY
              value: "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEAy5+9OXdqIWMjMPnlnB3oKn6cZuqOrtXh/8/TrFy6LNM=\n-----END PUBLIC KEY-----"
            - name: SA_PRIVATE_KEY
              value: "SA_PRIVATE_KEY_LAB"
            - name: DB_PASSWORD
              value: "DB_PASSWORD"
      serviceAccountName: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emr-outpatient
  namespace: default
spec:
  selector:
    matchLabels:
      app: emr-outpatient
  template:
    metadata:
      labels:
        app: emr-outpatient
    spec:
      containers:
        - image: leocardhio21/emr-outpatient:latest
          imagePullPolicy: Always
          name: emr-outpatient
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "600m"
          livenessProbe:
            httpGet:
              path: /
              port: 8082
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          ports:
            - containerPort: 8082
              protocol: TCP
          envFrom:
            - configMapRef:
                name: emr-config
          env:
            - name: KMS_KEY_NAME
              value: "mongo-symmetric-key"
            - name: JWT_PUBLIC_KEY
              value: "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEAy5+9OXdqIWMjMPnlnB3oKn6cZuqOrtXh/8/TrFy6LNM=\n-----END PUBLIC KEY-----"
            - name: SA_PRIVATE_KEY
              value: "SA_PRIVATE_KEY_LAB"
            - name: DB_PASSWORD
              value: "DB_PASSWORD"
            - name: LAB_SERVICE_URL
              value: "http://emr-lab.default.svc.cluster.local:8081"
            - name: PHARMACY_SERVICE_URL
              value: "http://emr-pharmacy.default.svc.cluster.local:8083"
            - name: RADIOLOGY_SERVICE_URL
              value: "http://emr-radiology.default.svc.cluster.local:8084"
              
      serviceAccountName: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emr-pharmacy
  namespace: default
spec:
  selector:
    matchLabels:
      app: emr-pharmacy
  template:
    metadata:
      labels:
        app: emr-pharmacy
    spec:
      containers:
        - image: leocardhio21/emr-pharmacy:latest
          imagePullPolicy: Always
          name: emr-pharmacy
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "600m"
          livenessProbe:
            httpGet:
              path: /
              port: 8083
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          ports:
            - containerPort: 8083
              protocol: TCP
          envFrom:
            - configMapRef:
                name: emr-config
          env:
            - name: KMS_KEY_NAME
              value: "mongo-symmetric-key"
            - name: JWT_PUBLIC_KEY
              value: "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEAy5+9OXdqIWMjMPnlnB3oKn6cZuqOrtXh/8/TrFy6LNM=\n-----END PUBLIC KEY-----"
            - name: SA_PRIVATE_KEY
              value: "SA_PRIVATE_KEY_LAB"
            - name: DB_PASSWORD
              value: "DB_PASSWORD"
      serviceAccountName: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emr-radiology
  namespace: default
spec:
  selector:
    matchLabels:
      app: emr-radiology
  template:
    metadata:
      labels:
        app: emr-radiology
    spec:
      containers:
        - image: leocardhio21/emr-radiology:latest
          imagePullPolicy: Always
          name: emr-radiology
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "600m"
          livenessProbe:
            httpGet:
              path: /
              port: 8084
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          ports:
            - containerPort: 8084
              protocol: TCP
          envFrom:
            - configMapRef:
                name: emr-config
          env:
            - name: KMS_KEY_NAME
              value: "mongo-symmetric-key"
            - name: JWT_PUBLIC_KEY
              value: "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEAy5+9OXdqIWMjMPnlnB3oKn6cZuqOrtXh/8/TrFy6LNM=\n-----END PUBLIC KEY-----"
            - name: SA_PRIVATE_KEY
              value: "SA_PRIVATE_KEY_LAB"
            - name: DB_PASSWORD
              value: "DB_PASSWORD"
      serviceAccountName: default
---