apiVersion: apps/v1
kind: Deployment
metadata:
  name: emr-auth
  namespace: default
spec:
  selector:
    matchLabels:
      app: emr-auth
  template:
    metadata:
      labels:
        app: emr-auth
    spec:
      containers:
        - image: leocardhio21/emr-auth
          imagePullPolicy: IfNotPresent
          name: emr-auth
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emr-lab
  namespace: default
spec:
  selector:
    matchLabels:
      app: emr-lab
  template:
    metadata:
      labels:
        app: emr-lab
    spec:
      containers:
        - image: leocardhio21/emr-lab
          imagePullPolicy: IfNotPresent
          name: emr-lab
          ports:
            - containerPort: 8081
              protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emr-outpatient
  namespace: default
spec:
  selector:
    matchLabels:
      app: emr-outpatient
  template:
    metadata:
      labels:
        app: emr-outpatient
    spec:
      containers:
        - image: leocardhio21/emr-outpatient
          imagePullPolicy: IfNotPresent
          name: emr-outpatient
          ports:
            - containerPort: 8082
              protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emr-pharmacy
  namespace: default
spec:
  selector:
    matchLabels:
      app: emr-pharmacy
  template:
    metadata:
      labels:
        app: emr-pharmacy
    spec:
      containers:
        - image: leocardhio21/emr-pharmacy
          imagePullPolicy: IfNotPresent
          name: emr-pharmacy
          ports:
            - containerPort: 8083
              protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emr-radiology
  namespace: default
spec:
  selector:
    matchLabels:
      app: emr-radiology
  template:
    metadata:
      labels:
        app: emr-radiology
    spec:
      containers:
        - image: leocardhio21/emr-radiology
          imagePullPolicy: IfNotPresent
          name: emr-radiology
          ports:
            - containerPort: 8084
              protocol: TCP
---